spring.application.name=busquedas
server.port=8085
# OpenSearch
opensearch.url=${OPENSEARCH_URL:http://opensearch:9200}
opensearch.index.read=games-read
opensearch.index.write=games-write
# RabbitMQ
spring.rabbitmq.host=${RABBITMQ_HOST:rabbitmq}
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
#busquedas.rabbit.exchange=catalog.events
#busquedas.rabbit.queue=busqueda.catalog.games
#busquedas.rabbit.routing.created=catalog.game.created
# Suggest
busquedas.suggest.min-chars=2
#busquedas.suggest.default-size=4

