opensearch.url=http://opensearch:9200
spring.rabbitmq.host=${SPRING_RABBITMQ_HOST:rabbitmq}
spring.rabbitmq.port=5672
spring.rabbitmq.username=${SPRING_RABBITMQ_USERNAME:trung}
spring.rabbitmq.password=${SPRING_RABBITMQ_PASSWORD:tu_password}