# =====================================
# CONFIGURACION - PUBLICACIONES SERVICE
# =====================================
spring.application.name=publicaciones
server.port=8084
# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
# lo quito que es una locura cuando hago sync/games
spring.jpa.show-sql=false 
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# =====================================
# MONGODB CONFIGURATION
# =====================================
spring.mongodb.host=mongo
spring.mongodb.port=27017
spring.mongodb.username=${MONGO_USER}
spring.mongodb.password=${MONGO_PASSWORD}
spring.mongodb.database=publicaciones_db
spring.mongodb.authentication-database=admin
# =====================================
# RABBITMQ
# =====================================
spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_DEFAULT_USER:guest}
spring.rabbitmq.password=${RABBITMQ_DEFAULT_PASS:guest}