# =====================================
# CONFIGURACION - PUBLICACIONES SERVICE
# =====================================
spring.application.name=publicaciones
server.port=8084
# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
# =====================================
# MONGODB CONFIGURATION (DOCKER)
# =====================================
# MongoDB URI with authentication against admin and specific database for platform
spring.mongodb.host=mongo
spring.mongodb.port=27017
spring.mongodb.username=${MONGO_USER}
spring.mongodb.password=${MONGO_PASSWORD}
spring.mongodb.database=publicaciones_db
spring.mongodb.authentication-database=admin
# =====================================
# RABBITMQ (DOCKER)
# =====================================
messaging.rabbitmq.enabled=true
spring.rabbitmq.host=${SPRING_RABBITMQ_HOST}
spring.rabbitmq.port=5672
spring.rabbitmq.username=${SPRING_RABBITMQ_USERNAME}
spring.rabbitmq.password=${SPRING_RABBITMQ_PASSWORD}
# =====================================
# LOGGING
# =====================================
logging.level.root=INFO
logging.level.org.springframework.web=INFO
logging.level.com.gamelist.catalogo=INFO
# Evitar que Hibernate imprima las sentencias SQL y los valores bind en la salida
logging.level.org.hibernate.SQL=INFO
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=INFO
