# Perfil docker para comunicacion entre microservicios por DNS interno de Docker
services.catalogo.url=http://catalogo:8082
services.publicaciones.url=http://publicaciones:8084
services.biblioteca.url=http://biblioteca:8083

