# =====================================
# CONFIGURACION - PUBLICACIONES SERVICE
# =====================================
spring.application.name=publicaciones
server.port=8084
# =====================================
# MONGODB CONFIGURATION (DOCKER)
# =====================================
# MongoDB URI with authentication against admin and specific database for platform
spring.mongodb.host=mongo
spring.mongodb.port=27017
spring.mongodb.username=${MONGO_USER}
spring.mongodb.password=${MONGO_PASSWORD}
spring.mongodb.database=publicaciones_db
spring.mongodb.authentication-database=admin
spring.mongodb.representation.uuid=standard
# =====================================
# RABBITMQ (DOCKER) - variables unificadas con el resto de microservicios
# =====================================
messaging.rabbitmq.enabled=true
spring.rabbitmq.host=${SPRING_RABBITMQ_HOST}
spring.rabbitmq.port=5672
spring.rabbitmq.username=${SPRING_RABBITMQ_USERNAME}
spring.rabbitmq.password=${SPRING_RABBITMQ_PASSWORD}
spring.rabbitmq.publisher-confirm-type=correlated
spring.rabbitmq.publisher-returns=true
# =====================================
# LOGGING
# =====================================
logging.level.root=INFO
logging.level.org.springframework.web=INFO
logging.level.com.gamelisto.publicaciones=INFO