# =====================================
# CONFIGURACION DOCKER - SOCIAL SERVICE
# =====================================
# NEO4J
spring.neo4j.uri=${NEO4J_URI:bolt://neo4j:7687}
spring.neo4j.authentication.username=${NEO4J_USER:neo4j}
spring.neo4j.authentication.password=${NEO4J_PASSWORD:password}
# RABBITMQ
spring.rabbitmq.host=${SPRING_RABBITMQ_HOST:rabbitmq}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_DEFAULT_USER:guest}
spring.rabbitmq.password=${RABBITMQ_DEFAULT_PASS:guest}
messaging.rabbitmq.enabled=true

